Repository ArkEcosystem/typescript-client, pull requests merged in 2019-09, with the labels that each got.

#54 feat: crypto endpoint
  __tests__/mocks/node.ts
  __tests__/resources/node.test.ts
  src/resources/node.ts
Labels: Complexity: Low, Type: Feature

#55 release: 1.0.2
  .codacy.yml
  CHANGELOG.md
  package.json
Labels: Complexity: Low, Type: Release

#57 chore: fix changelog typo
  CHANGELOG.md
Labels: Complexity: Low, Type: Task

#59 chore: update deps
  package.json
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#60 feat: add rounds api
  __tests__/mocks/index.ts
  __tests__/mocks/rounds.ts
  __tests__/resources/rounds.test.ts
  src/resources/index.ts
  src/resources/rounds.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Feature

#62 ci: setup github action workflow for testing
  .circleci/config.yml
  .github/workflows/test.yml
Labels: Complexity: Medium

#63 ci: trigger workflows for push.* and pull_request.* events
  .github/workflows/test.yml
Labels: Complexity: Low

#65 ci: adjust job triggers
  .github/workflows/test.yml
Labels: Complexity: Low
