Repository ArkEcosystem/typescript-client, pull requests merged in 2019-01, with the labels that each got.

#26 fix: use the correct API version header
  CHANGELOG.md
  __tests__/http.test.js
  lib/http.js
  package.json
Labels: Status: Blocked

#28 refactor: isHttps property when finding peers
  CHANGELOG.md
  __tests__/client.test.js
  lib/index.js
  package.json
Labels: Status: Needs Review, Type: Refactor

#29 feat: transaction fees v2 endpoint
  CHANGELOG.md
  __tests__/mocks/v2/transactions.js
  __tests__/resources/v2/transactions.test.js
  lib/resources/v2/transactions.js
  package.json
Labels: Status: Needs Review, Type: Feature
