Repository ArkEcosystem/typescript-client, pull requests merged in 2020-02, with the labels that each got.

#95 types: available resources
  src/connection-manager.ts
  src/connection.ts
  src/errors.ts
  src/resources/bridgechains.ts
  src/resources/businesses.ts
  src/resources/index.ts
  src/resources/locks.ts
  src/resources/node.ts
  tslint.json
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved

#98 chore: update all dependencies
  package.json
  src/connection.ts
  yarn.lock
Labels: Complexity: Medium, Type: Task

#99 types: resource methods
  __tests__/mocks/blocks.ts
  __tests__/mocks/delegates.ts
  __tests__/mocks/node.ts
  __tests__/mocks/transactions.ts
  __tests__/mocks/wallets.ts
  __tests__/resources/blocks.test.ts
  __tests__/resources/delegates.test.ts
  __tests__/resources/node.test.ts
  __tests__/resources/transactions.test.ts
  __tests__/resources/wallets.test.ts
  src/connection.ts
  src/index.ts
  src/interfaces.ts
  src/resources/blocks.ts
  src/resources/bridgechains.ts
  src/resources/businesses.ts
  src/resources/delegates.ts
  src/resources/locks.ts
  src/resources/node.ts
  src/resources/peers.ts
  src/resources/resource.ts
  src/resources/rounds.ts
  src/resources/transactions.ts
  src/resources/votes.ts
  src/resources/wallets.ts
  src/resourcesTypes/blocks.ts
  src/resourcesTypes/bridgechains.ts
  src/resourcesTypes/businesses.ts
  src/resourcesTypes/delegates.ts
  src/resourcesTypes/index.ts
  src/resourcesTypes/locks.ts
  src/resourcesTypes/peers.ts
  src/resourcesTypes/transactions.ts
  src/resourcesTypes/wallets.ts
  tslint.json
Labels: Bounty: Tier 1, Complexity: Undetermined, Status: Contributor Approved
