Repository ArkEcosystem/typescript-client, pull requests merged in 2020-03, with the labels that each got.

#101 types: API responses
  __tests__/mocks/node.ts
  __tests__/resources/node.test.ts
  src/connection.ts
  src/errors.ts
  src/interfaces.ts
  src/resources/blocks.ts
  src/resources/bridgechains.ts
  src/resources/businesses.ts
  src/resources/delegates.ts
  src/resources/locks.ts
  src/resources/node.ts
  src/resources/peers.ts
  src/resources/rounds.ts
  src/resources/transactions.ts
  src/resources/votes.ts
  src/resources/wallets.ts
  src/resourcesTypes/blocks.ts
  src/resourcesTypes/bridgechains.ts
  src/resourcesTypes/businesses.ts
  src/resourcesTypes/delegates.ts
  src/resourcesTypes/locks.ts
  src/resourcesTypes/node.ts
  src/resourcesTypes/peers.ts
  src/resourcesTypes/transactions.ts
  src/resourcesTypes/wallets.ts
Labels: Bounty: Tier 2, Complexity: Medium, Status: Contributor Approved, Status: Needs Review

#100 chore: move bridgechains/{id} endpoint
  __tests__/mocks/bridgechains.ts
  __tests__/mocks/businesses.ts
  __tests__/resources/bridgechains.test.ts
  __tests__/resources/businesses.test.ts
  src/resources/bridgechains.ts
  src/resources/businesses.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Task

#107 fix: add and adjust various transaction typings
  __tests__/resources/transactions.test.ts
  src/connection.ts
  src/interfaces.ts
  src/resources/index.ts
  src/resources/transactions.ts
  src/resourcesTypes/transactions.ts
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved

#110 types: simplify pagination
  src/interfaces.ts
  src/resources/blocks.ts
  src/resources/bridgechains.ts
  src/resources/businesses.ts
  src/resources/delegates.ts
  src/resources/locks.ts
  src/resources/node.ts
  src/resources/peers.ts
  src/resources/rounds.ts
  src/resources/transactions.ts
  src/resources/wallets.ts
Labels: Complexity: Medium, Status: Contributor Approved, Type: Bugfix
